name = "explore-scripture"

# Pages configuration
pages_build_output_dir = "_site"

# Workers configuration (for advanced features)
main = "src/worker.js"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]

# Account settings (use environment variable or local config)
account_id = "${CLOUDFLARE_ACCOUNT_ID}"

# Environment variables
[vars]
ENVIRONMENT = "production"

# KV Namespaces for caching (use environment variables or local config)
[[kv_namespaces]]
binding = "CACHE"
id = "${CLOUDFLARE_KV_CACHE_ID}"
preview_id = "${CLOUDFLARE_KV_CACHE_PREVIEW_ID}"

[[kv_namespaces]]
binding = "ENTITIES"
id = "${CLOUDFLARE_KV_ENTITIES_ID}"
preview_id = "${CLOUDFLARE_KV_ENTITIES_PREVIEW_ID}"

# Static assets configuration (legacy but works in local dev)
[site]
bucket = "_site"

# Build configuration - disabled for direct deploy
# [build]
# command = "npm run build:workers-temp"
# cwd = "./"

# Development settings
[dev]
local_protocol = "https"
port = 8787

# Routes - removed problematic pages.dev route

# Security headers
[env.production]
[env.production.vars]
CSP_HEADER = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https: https://i.ytimg.com; connect-src 'self' https://api.esv.org https://www.biblegateway.com https://bible-api.com; frame-src https://www.youtube.com https://www.biblegateway.com https://enduringword.com https://biblehub.com; object-src 'none'; base-uri 'self'; form-action 'self';"

# Analytics - disabled until enabled in dashboard
# [[analytics_engine_datasets]]
# binding = "BIBLE_ANALYTICS"
# dataset = "explore_scripture_analytics"