const META = {
  scope:
    'High-coverage list of named people-groups in the Protestant Bible (66 books), including (1) ethnic/national/tribal groups and (2) socio-religious/political/civic groups. Not exhaustive of every one-off city demonym (e.g., men of <town>) or every regional adjective.',
  schema: {
    id: 'stable-ish slug id',
    name: 'display name',
    category:
      'covenant_identity | collective_label | tribe | priestly_levitical | ethnic_nation | empire_people | regional_demonym | table_of_nations_people | clan | religious_sect | political_party | religious_office | civic_class | military_class | movement',
    testament: 'OT | NT | Both',
    alt_names: 'array of alternate names/labels',
    notes: 'short clarifying notes',
    example_refs: 'representative references (not exhaustive)',
  },
};

const RAW_GROUPS = [
  {
    id: 'covenant_hebrews',
    name: 'Hebrews',
    category: 'covenant_identity',
    testament: 'Both',
    alt_names: ['Hebrew'],
    notes: "An identity label used for Abraham's descendants / Israelites, and also used in NT contexts.",
    example_refs: ['Genesis 14', 'Exodus 1', 'Philippians 3'],
  },
  {
    id: 'covenant_israelites',
    name: 'Israelites',
    category: 'covenant_identity',
    testament: 'Both',
    alt_names: ['Children of Israel', 'Sons of Israel', 'House of Israel'],
    notes: 'Covenant people descended from Jacob/Israel; also used as a national label.',
    example_refs: ['Exodus', 'Judges', 'Romans 9'],
  },
  {
    id: 'covenant_judeans',
    name: 'Judeans / Judahites',
    category: 'covenant_identity',
    testament: 'Both',
    alt_names: ['Judeans', 'Judahites', 'Men of Judah'],
    notes: 'People associated with Judah / the southern kingdom / later Judea.',
    example_refs: ['2 Kings', 'Nehemiah', 'John 7'],
  },
  {
    id: 'covenant_jews',
    name: 'Jews',
    category: 'covenant_identity',
    testament: 'Both',
    alt_names: ['Jew', 'The Jewish people'],
    notes: 'Prominent post-exile label; central in the NT.',
    example_refs: ['Esther', 'John', 'Acts'],
  },
  {
    id: 'covenant_samaritans',
    name: 'Samaritans',
    category: 'covenant_identity',
    testament: 'NT',
    alt_names: ['People of Samaria'],
    notes: 'Distinct community related to Israel with separate temple/traditions in NT era.',
    example_refs: ['John 4', 'Luke 10', 'Acts 8'],
  },
  {
    id: 'collective_gentiles',
    name: 'Gentiles / The Nations',
    category: 'collective_label',
    testament: 'Both',
    alt_names: ['Nations', 'Heathen (older translations)'],
    notes: 'Collective label for non-Israel peoples; often theological category as well as ethnic.',
    example_refs: ['Genesis 12', 'Isaiah 49', 'Acts 10'],
  },
  {
    id: 'nt_proselytes',
    name: 'Proselytes',
    category: 'civic_class',
    testament: 'NT',
    alt_names: ['Proselyte'],
    notes: 'Gentiles who fully converted to Judaism (term appears explicitly).',
    example_refs: ['Matthew 23', 'Acts 2'],
  },
  {
    id: 'nt_godfearers',
    name: 'God-fearers',
    category: 'civic_class',
    testament: 'NT',
    alt_names: ['Worshipers of God', 'Those who fear God'],
    notes: 'Gentiles attached to synagogue worship without full conversion (NT phrasing).',
    example_refs: ['Acts 10', 'Acts 13'],
  },
  {
    id: 'tribe_reuben',
    name: 'Reuben',
    category: 'tribe',
    testament: 'OT',
    alt_names: ['Reubenites'],
    notes: 'One of the twelve tribes of Israel.',
    example_refs: ['Numbers 1', 'Joshua 13'],
  },
  {
    id: 'tribe_simeon',
    name: 'Simeon',
    category: 'tribe',
    testament: 'OT',
    alt_names: ['Simeonites'],
    notes: 'One of the twelve tribes of Israel.',
    example_refs: ['Numbers 1', 'Joshua 19'],
  },
  {
    id: 'tribe_levi',
    name: 'Levi',
    category: 'tribe',
    testament: 'OT',
    alt_names: ['Levites'],
    notes: 'Tribe set apart for priestly/temple service; also functions as a people-group label.',
    example_refs: ['Exodus 32', 'Numbers 3'],
  },
  {
    id: 'tribe_judah',
    name: 'Judah',
    category: 'tribe',
    testament: 'OT',
    alt_names: ['Judahites'],
    notes: "Tribe associated with Davidic kingship; later identity overlaps with 'Jews/Judeans'.",
    example_refs: ['Genesis 49', '2 Samuel 2'],
  },
  {
    id: 'tribe_dan',
    name: 'Dan',
    category: 'tribe',
    testament: 'OT',
    alt_names: ['Danites'],
    notes: 'One of the twelve tribes of Israel.',
    example_refs: ['Judges 18', 'Numbers 2'],
  },
  {
    id: 'tribe_naphtali',
    name: 'Naphtali',
    category: 'tribe',
    testament: 'OT',
    alt_names: ['Naphtalites'],
    notes: 'One of the twelve tribes of Israel.',
    example_refs: ['Joshua 19', 'Judges 4'],
  },
  {
    id: 'tribe_gad',
    name: 'Gad',
    category: 'tribe',
    testament: 'OT',
    alt_names: ['Gadites'],
    notes: 'One of the twelve tribes of Israel.',
    example_refs: ['Numbers 32', 'Joshua 13'],
  },
  {
    id: 'tribe_asher',
    name: 'Asher',
    category: 'tribe',
    testament: 'OT',
    alt_names: ['Asherites'],
    notes: 'One of the twelve tribes of Israel.',
    example_refs: ['Joshua 19', 'Judges 1'],
  },
  {
    id: 'tribe_issachar',
    name: 'Issachar',
    category: 'tribe',
    testament: 'OT',
    alt_names: ['Issacharites'],
    notes: 'One of the twelve tribes of Israel.',
    example_refs: ['1 Chronicles 12', 'Numbers 1'],
  },
  {
    id: 'tribe_zebulun',
    name: 'Zebulun',
    category: 'tribe',
    testament: 'OT',
    alt_names: ['Zebulunites'],
    notes: 'One of the twelve tribes of Israel.',
    example_refs: ['Joshua 19', 'Judges 5'],
  },
  {
    id: 'tribe_benjamin',
    name: 'Benjamin',
    category: 'tribe',
    testament: 'OT',
    alt_names: ['Benjaminites'],
    notes: 'One of the twelve tribes of Israel.',
    example_refs: ['Judges 19-21', '1 Samuel 9'],
  },
  {
    id: 'tribe_ephraim',
    name: 'Ephraim',
    category: 'tribe',
    testament: 'OT',
    alt_names: ['Ephraimites'],
    notes: "Joseph-tribe; also used as a label for the northern kingdom ('Ephraim').",
    example_refs: ['Joshua 16', 'Hosea'],
  },
  {
    id: 'tribe_manasseh',
    name: 'Manasseh',
    category: 'tribe',
    testament: 'OT',
    alt_names: ['Manassites'],
    notes: 'Joseph-tribe; includes half-tribe east of Jordan.',
    example_refs: ['Joshua 13', 'Joshua 17'],
  },
  {
    id: 'priestly_levites',
    name: 'Levites',
    category: 'priestly_levitical',
    testament: 'Both',
    alt_names: [],
    notes: 'Tribal/service group associated with sanctuary/temple duties.',
    example_refs: ['Numbers 3', 'Luke 10', 'Acts 4'],
  },
  {
    id: 'priestly_aaronic',
    name: 'Aaronic Priests (Sons of Aaron)',
    category: 'priestly_levitical',
    testament: 'Both',
    alt_names: ['Priests'],
    notes: "Priestly line within Levi; 'priests\' often broader office label too.",
    example_refs: ['Leviticus', 'Hebrews 7'],
  },
  {
    id: 'priestly_kohathites',
    name: 'Kohathites',
    category: 'priestly_levitical',
    testament: 'OT',
    alt_names: [],
    notes: 'Levitical clan.',
    example_refs: ['Numbers 4', '1 Chronicles 6'],
  },
  {
    id: 'priestly_gershonites',
    name: 'Gershonites',
    category: 'priestly_levitical',
    testament: 'OT',
    alt_names: ['Gershonites'],
    notes: 'Levitical clan.',
    example_refs: ['Numbers 4', '1 Chronicles 6'],
  },
  {
    id: 'priestly_merarites',
    name: 'Merarites',
    category: 'priestly_levitical',
    testament: 'OT',
    alt_names: [],
    notes: 'Levitical clan.',
    example_refs: ['Numbers 4', '1 Chronicles 6'],
  },
  {
    id: 'priestly_zadokites',
    name: 'Zadokites (House of Zadok)',
    category: 'priestly_levitical',
    testament: 'OT',
    alt_names: [],
    notes: 'Priestly lineage associated with Zadok in later OT history and temple discussions.',
    example_refs: ['2 Samuel 8', 'Ezekiel 44'],
  },
  {
    id: 'empire_assyrians',
    name: 'Assyrians',
    category: 'empire_people',
    testament: 'OT',
    alt_names: ['Asshur (as a people/region label in genealogies)'],
    notes: 'Major Mesopotamian imperial people.',
    example_refs: ['2 Kings 17', 'Isaiah 10'],
  },
  {
    id: 'empire_babylonians',
    name: 'Babylonians',
    category: 'empire_people',
    testament: 'OT',
    alt_names: ['Chaldeans (often closely associated)'],
    notes: 'Imperial people associated with Babylon and the exile period.',
    example_refs: ['2 Kings 24-25', 'Daniel 1'],
  },
  {
    id: 'empire_chaldeans',
    name: 'Chaldeans',
    category: 'empire_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Often linked with Babylon; also appears as raiders in Job.',
    example_refs: ['Daniel 2', 'Job 1'],
  },
  {
    id: 'empire_persians',
    name: 'Persians',
    category: 'empire_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Imperial people in the post-exilic period.',
    example_refs: ['Ezra', 'Esther', 'Daniel 6'],
  },
  {
    id: 'empire_medes',
    name: 'Medes',
    category: 'empire_people',
    testament: 'Both',
    alt_names: ['Median'],
    notes: 'Appears in OT empire context and in NT diaspora lists.',
    example_refs: ['Daniel 5-6', 'Acts 2'],
  },
  {
    id: 'empire_parthians',
    name: 'Parthians',
    category: 'empire_people',
    testament: 'NT',
    alt_names: [],
    notes: 'Named in NT diaspora roll-call.',
    example_refs: ['Acts 2'],
  },
  {
    id: 'empire_greeks',
    name: 'Greeks',
    category: 'empire_people',
    testament: 'NT',
    alt_names: ['Hellenes', 'Greek-speaking peoples (contextual)'],
    notes: 'Ethnic/cultural label; sometimes broad shorthand for the Gentile world in NT rhetoric.',
    example_refs: ['John 12', 'Acts 17', 'Romans 1'],
  },
  {
    id: 'empire_romans',
    name: 'Romans',
    category: 'empire_people',
    testament: 'NT',
    alt_names: ['Roman'],
    notes: 'Imperial people/citizens; appears widely in NT.',
    example_refs: ['Acts 16', 'Romans 1', 'Acts 28'],
  },
  {
    id: 'ethnic_egyptians',
    name: 'Egyptians',
    category: 'ethnic_nation',
    testament: 'Both',
    alt_names: ['Mizraim (genealogical label)'],
    notes: 'Major neighboring nation; also appears in NT lists.',
    example_refs: ['Exodus', 'Isaiah 19', 'Acts 2'],
  },
  {
    id: 'ethnic_philistines',
    name: 'Philistines',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'Coastal people frequently in conflict with Israel.',
    example_refs: ['Judges', '1 Samuel'],
  },
  {
    id: 'ethnic_caphtorim',
    name: 'Caphtorim',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Caphtorites (as a gentilic form)'],
    notes: 'People associated with Caphtor; connected to Philistine origin traditions.',
    example_refs: ['Deuteronomy 2', 'Amos 9'],
  },
  {
    id: 'ethnic_cherethites',
    name: 'Cherethites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes:
      'Often linked with coastal/Philistine contexts; appears as a distinct group in royal/military settings.',
    example_refs: ['1 Samuel 30', '2 Samuel 8'],
  },
  {
    id: 'ethnic_pelethites',
    name: 'Pelethites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: "Often paired with Cherethites as elite guard group in David's administration.",
    example_refs: ['2 Samuel 8', '1 Kings 1'],
  },
  {
    id: 'ethnic_edemites',
    name: 'Edomites',
    category: 'ethnic_nation',
    testament: 'Both',
    alt_names: ['Edom', 'Idumeans (later form)'],
    notes: 'Descendants of Esau; recurring neighboring people.',
    example_refs: ['Genesis 36', 'Obadiah', 'Mark 3 (Idumea as region)'],
  },
  {
    id: 'ethnic_moabites',
    name: 'Moabites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Moab'],
    notes: 'Neighbor nation east of the Jordan; central in Ruth.',
    example_refs: ['Numbers 22', 'Ruth'],
  },
  {
    id: 'ethnic_ammonites',
    name: 'Ammonites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Ammon'],
    notes: 'Neighbor nation east of the Jordan.',
    example_refs: ['Judges 10-11', '2 Samuel 10'],
  },
  {
    id: 'ethnic_ishmaelites',
    name: 'Ishmaelites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'People descended from Ishmael; appears in patriarchal narratives.',
    example_refs: ['Genesis 37'],
  },
  {
    id: 'ethnic_midianites',
    name: 'Midianites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Midian'],
    notes: 'Desert people; prominent in Exodus/Judges era narratives.',
    example_refs: ['Exodus 2-3', 'Judges 6-8'],
  },
  {
    id: 'ethnic_amalekites',
    name: 'Amalekites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Amalek'],
    notes: 'Recurring hostile people group in wilderness and monarchy narratives.',
    example_refs: ['Exodus 17', '1 Samuel 15'],
  },
  {
    id: 'ethnic_arameans',
    name: 'Arameans (Syrians)',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Syrians', 'Aram'],
    notes: 'Northern neighbors; appears as kingdom(s) and as ethnic label.',
    example_refs: ['1 Kings 20', '2 Kings 5'],
  },
  {
    id: 'ethnic_canaanites',
    name: 'Canaanites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Canaan'],
    notes: 'Umbrella label for peoples in the land; also one of the classic -ites.',
    example_refs: ['Genesis 12', 'Joshua 3'],
  },
  {
    id: 'ethnic_amorites',
    name: 'Amorites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'Prominent Canaan-region people group in conquest-era lists.',
    example_refs: ['Genesis 15', 'Joshua 10'],
  },
  {
    id: 'ethnic_hittites',
    name: 'Hittites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'People group appearing in patriarchal and conquest-era contexts.',
    example_refs: ['Genesis 23', 'Joshua 1'],
  },
  {
    id: 'ethnic_jebusites',
    name: 'Jebusites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'Associated with Jerusalem (Jebus) prior to David\'s conquest.',
    example_refs: ['Joshua 15', '2 Samuel 5'],
  },
  {
    id: 'ethnic_perizzites',
    name: 'Perizzites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'Included in classic land peoples lists.',
    example_refs: ['Genesis 13', 'Joshua 3'],
  },
  {
    id: 'ethnic_girgashites',
    name: 'Girgashites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'Included in classic land peoples lists.',
    example_refs: ['Deuteronomy 7', 'Joshua 3'],
  },
  {
    id: 'ethnic_hivites',
    name: 'Hivites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'Included in classic land peoples lists; associated with Gibeonites in some contexts.',
    example_refs: ['Genesis 34', 'Joshua 9'],
  },
  {
    id: 'ethnic_kenites',
    name: 'Kenites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'Group connected with Midian-related narratives and later settlement among Israel.',
    example_refs: ['Numbers 24', 'Judges 1'],
  },
  {
    id: 'ethnic_kenizzites',
    name: 'Kenizzites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Kenezites'],
    notes: 'Named among land peoples; also appears as a gentilic/family link (e.g., Caleb).',
    example_refs: ['Genesis 15', 'Numbers 32'],
  },
  {
    id: 'ethnic_kadmonites',
    name: 'Kadmonites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'Named among land peoples in patriarchal promise lists.',
    example_refs: ['Genesis 15'],
  },
  {
    id: 'ethnic_gibeonites',
    name: 'Gibeonites',
    category: 'clan',
    testament: 'OT',
    alt_names: [],
    notes: 'Treaty community in Joshua; later appears as distinct group.',
    example_refs: ['Joshua 9', '2 Samuel 21'],
  },
  {
    id: 'ethnic_sidonian',
    name: 'Sidonians',
    category: 'ethnic_nation',
    testament: 'Both',
    alt_names: ['Sidon'],
    notes: 'Phoenician city-people; appears in OT and NT.',
    example_refs: ['Judges 10', 'Mark 7', 'Acts 12'],
  },
  {
    id: 'ethnic_tyrian',
    name: 'Tyrians',
    category: 'ethnic_nation',
    testament: 'Both',
    alt_names: ['Tyre'],
    notes: 'Phoenician city-people; appears in OT and NT.',
    example_refs: ['1 Kings 5', 'Matthew 11', 'Acts 21'],
  },
  {
    id: 'giants_rephaim',
    name: 'Rephaim',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'A people-group term associated with giant traditions and a region name in some texts.',
    example_refs: ['Genesis 14', 'Deuteronomy 3'],
  },
  {
    id: 'giants_anakim',
    name: 'Anakim (Anakites)',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Anakites'],
    notes: 'Giant-associated people in conquest narratives.',
    example_refs: ['Numbers 13', 'Joshua 11'],
  },
  {
    id: 'giants_emim',
    name: 'Emim',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'Group associated with Moabite giant traditions.',
    example_refs: ['Deuteronomy 2'],
  },
  {
    id: 'giants_zamzummim',
    name: 'Zamzummim',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'Group associated with Ammonite giant traditions.',
    example_refs: ['Deuteronomy 2'],
  },
  {
    id: 'ethnic_horites',
    name: 'Horites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'People associated with Seir/Edom-region traditions.',
    example_refs: ['Genesis 14', 'Genesis 36'],
  },
  {
    id: 'ethnic_avvim',
    name: 'Avvim',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Avvites (gentilic form)'],
    notes: 'People mentioned in conquest/settlement contexts.',
    example_refs: ['Deuteronomy 2', 'Joshua 13'],
  },
  {
    id: 'africa_cushites',
    name: 'Cushites',
    category: 'ethnic_nation',
    testament: 'Both',
    alt_names: ['Ethiopians (common translation)'],
    notes:
      'African-region people group; also appears indirectly in NT-related contexts (e.g., Ethiopian official).',
    example_refs: ['Numbers 12', 'Isaiah 18', 'Acts 8'],
  },
  {
    id: 'africa_lubim',
    name: 'Lubim',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Libyans (often)'],
    notes: 'People group named in some OT historical lists.',
    example_refs: ['2 Chronicles 12', '2 Chronicles 16'],
  },
  {
    id: 'africa_sukkim',
    name: 'Sukkim',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: [],
    notes: 'Named in an OT coalition list.',
    example_refs: ['2 Chronicles 12'],
  },
  {
    id: 'nt_cyrenians',
    name: 'Cyrenians',
    category: 'regional_demonym',
    testament: 'NT',
    alt_names: ['Libya near Cyrene (phrasing)'],
    notes: 'Diaspora/regional label in NT.',
    example_refs: ['Acts 2', 'Acts 6', 'Acts 11'],
  },
  {
    id: 'regional_cappadocians',
    name: 'Cappadocians',
    category: 'regional_demonym',
    testament: 'NT',
    alt_names: [],
    notes: 'Region/people label in NT lists.',
    example_refs: ['Acts 2', '1 Peter 1'],
  },
  {
    id: 'regional_pontians',
    name: 'Pontians',
    category: 'regional_demonym',
    testament: 'NT',
    alt_names: ['Pontus (region)'],
    notes: 'Region/people label in NT.',
    example_refs: ['Acts 2', 'Acts 18', '1 Peter 1'],
  },
  {
    id: 'regional_asians',
    name: 'Asians (Roman province of Asia)',
    category: 'regional_demonym',
    testament: 'NT',
    alt_names: ['Asia (province)'],
    notes: "NT 'Asia\' is typically the Roman province in western Anatolia, not the modern continent label.",
    example_refs: ['Acts 2', 'Acts 19', '1 Corinthians 16'],
  },
  {
    id: 'regional_phrygians',
    name: 'Phrygians',
    category: 'regional_demonym',
    testament: 'NT',
    alt_names: ['Phrygia (region)'],
    notes: 'Region/people label in NT lists.',
    example_refs: ['Acts 2', 'Acts 16', 'Acts 18'],
  },
  {
    id: 'regional_pamphylians',
    name: 'Pamphylians',
    category: 'regional_demonym',
    testament: 'NT',
    alt_names: ['Pamphylia (region)'],
    notes: 'Region/people label in NT lists.',
    example_refs: ['Acts 2', 'Acts 13', 'Acts 14'],
  },
  {
    id: 'regional_cilicians',
    name: 'Cilicians',
    category: 'regional_demonym',
    testament: 'NT',
    alt_names: ['Cilicia (region)'],
    notes: 'Region/people label in NT.',
    example_refs: ['Acts 6', 'Acts 15', 'Acts 21'],
  },
  {
    id: 'regional_cretans',
    name: 'Cretans',
    category: 'regional_demonym',
    testament: 'NT',
    alt_names: ['Crete (island)'],
    notes: 'Named in NT diaspora list and later epistles.',
    example_refs: ['Acts 2', 'Titus 1'],
  },
  {
    id: 'regional_galatians',
    name: 'Galatians',
    category: 'regional_demonym',
    testament: 'NT',
    alt_names: ['Galatia (region)'],
    notes: 'Region/people label in NT letters and travel narratives.',
    example_refs: ['Acts 16', 'Galatians 1', '1 Peter 1'],
  },
  {
    id: 'regional_lycaonians',
    name: 'Lycaonians',
    category: 'regional_demonym',
    testament: 'NT',
    alt_names: ['Lycaonia (region)'],
    notes: 'Appears in Acts as a distinct language/people label.',
    example_refs: ['Acts 14'],
  },
  {
    id: 'regional_macedonians',
    name: 'Macedonians',
    category: 'regional_demonym',
    testament: 'NT',
    alt_names: ['Macedonia (region)'],
    notes: 'Distinct regional identity in NT mission narratives and letters.',
    example_refs: ['Acts 16', '2 Corinthians 8', 'Philippians 4'],
  },
  {
    id: 'regional_bithynians',
    name: 'Bithynians',
    category: 'regional_demonym',
    testament: 'NT',
    alt_names: ['Bithynia (region)'],
    notes: 'Region/people label in NT.',
    example_refs: ['Acts 16', '1 Peter 1'],
  },
  {
    id: 'nt_scythians',
    name: 'Scythians',
    category: 'ethnic_nation',
    testament: 'NT',
    alt_names: [],
    notes: 'Named as an ethnic extreme example in NT rhetoric.',
    example_refs: ['Colossians 3'],
  },
  {
    id: 'nt_barbarians',
    name: 'Barbarians',
    category: 'collective_label',
    testament: 'NT',
    alt_names: [],
    notes: 'Greco-Roman cultural label for non-Greek speakers; used in NT.',
    example_refs: ['Romans 1', 'Acts 28', '1 Corinthians 14'],
  },
  {
    id: 'religious_sect_pharisees',
    name: 'Pharisees',
    category: 'religious_sect',
    testament: 'NT',
    alt_names: [],
    notes: 'Second Temple Jewish sect prominent in the Gospels and Acts.',
    example_refs: ['Matthew 23', 'Acts 5', 'Acts 23'],
  },
  {
    id: 'religious_sect_sadducees',
    name: 'Sadducees',
    category: 'religious_sect',
    testament: 'NT',
    alt_names: [],
    notes: 'Second Temple Jewish sect associated with temple leadership.',
    example_refs: ['Matthew 22', 'Acts 5'],
  },
  {
    id: 'religious_office_scribes',
    name: 'Scribes',
    category: 'religious_office',
    testament: 'NT',
    alt_names: ['Teachers of the law (often)'],
    notes: 'Torah experts; appear as a recognizable group.',
    example_refs: ['Mark 2', 'Luke 5'],
  },
  {
    id: 'religious_office_lawyers',
    name: 'Lawyers (Torah experts)',
    category: 'religious_office',
    testament: 'NT',
    alt_names: ['Experts in the law'],
    notes: "Recognizable group in Jesus' controversies.",
    example_refs: ['Luke 10', 'Luke 11'],
  },
  {
    id: 'religious_office_chief_priests',
    name: 'Chief Priests',
    category: 'religious_office',
    testament: 'NT',
    alt_names: [],
    notes: 'Temple leadership grouping in the Gospels/Acts.',
    example_refs: ['Matthew 26', 'Acts 4'],
  },
  {
    id: 'religious_office_elders',
    name: 'Elders (Jewish leadership)',
    category: 'religious_office',
    testament: 'NT',
    alt_names: [],
    notes: 'Leadership group frequently paired with chief priests and scribes.',
    example_refs: ['Matthew 26', 'Acts 4'],
  },
  {
    id: 'political_party_herodians',
    name: 'Herodians',
    category: 'political_party',
    testament: 'NT',
    alt_names: [],
    notes: 'Political grouping aligned with Herodian interests.',
    example_refs: ['Mark 3', 'Mark 12'],
  },
  {
    id: 'political_party_zealots',
    name: 'Zealots',
    category: 'political_party',
    testament: 'NT',
    alt_names: [],
    notes: 'Political identity label; also used as a descriptor for Simon in the Twelve.',
    example_refs: ['Luke 6', 'Acts 1'],
  },
  {
    id: 'political_party_sicarii',
    name: 'Assassins (Sicarii)',
    category: 'political_party',
    testament: 'NT',
    alt_names: ['Sicarii (in some translations/notes)'],
    notes: 'Mentioned as a violent political group in Acts (translation varies).',
    example_refs: ['Acts 21'],
  },
  {
    id: 'movement_the_way',
    name: 'The Way',
    category: 'movement',
    testament: 'NT',
    alt_names: [],
    notes: 'Early Christian movement self-designation in Acts.',
    example_refs: ['Acts 9', 'Acts 19', 'Acts 24'],
  },
  {
    id: 'movement_christians',
    name: 'Christians',
    category: 'movement',
    testament: 'NT',
    alt_names: [],
    notes: 'Name applied to Jesus-followers (explicit in NT).',
    example_refs: ['Acts 11', 'Acts 26', '1 Peter 4'],
  },
  {
    id: 'movement_nazarenes',
    name: 'Nazarenes (as a label for Jesus-followers)',
    category: 'movement',
    testament: 'NT',
    alt_names: [],
    notes: 'Used as an external label for the Jesus movement in Acts.',
    example_refs: ['Acts 24'],
  },
  {
    id: 'civic_tax_collectors',
    name: 'Tax Collectors (Publicans)',
    category: 'civic_class',
    testament: 'NT',
    alt_names: ['Publicans'],
    notes: 'Recognizable social/occupational group in the Gospels.',
    example_refs: ['Matthew 9', 'Luke 19'],
  },
  {
    id: 'civic_freedmen',
    name: 'Freedmen',
    category: 'civic_class',
    testament: 'NT',
    alt_names: ['Synagogue of the Freedmen (phrase)'],
    notes: 'Appears as a named synagogue-associated grouping in Acts.',
    example_refs: ['Acts 6'],
  },
  {
    id: 'military_soldiers',
    name: 'Soldiers',
    category: 'military_class',
    testament: 'NT',
    alt_names: [],
    notes: 'Common NT social/military grouping.',
    example_refs: ['Luke 3', 'Matthew 27', 'Acts 10'],
  },
  {
    id: 'military_centurions',
    name: 'Centurions',
    category: 'military_class',
    testament: 'NT',
    alt_names: [],
    notes: 'Roman military officer class appearing repeatedly in NT narratives.',
    example_refs: ['Matthew 8', 'Acts 10', 'Acts 27'],
  },
  {
    id: 'temple_nethinim',
    name: 'Nethinim (Temple servants)',
    category: 'religious_office',
    testament: 'OT',
    alt_names: [],
    notes: 'Post-exilic temple service group named in Ezra/Nehemiah lists.',
    example_refs: ['Ezra 2', 'Nehemiah 7'],
  },
  {
    id: 'temple_gatekeepers',
    name: 'Gatekeepers (Temple)',
    category: 'religious_office',
    testament: 'OT',
    alt_names: [],
    notes: 'Recognizable temple guild/service grouping.',
    example_refs: ['1 Chronicles 9', 'Nehemiah 12'],
  },
  {
    id: 'temple_singers',
    name: 'Singers (Temple)',
    category: 'religious_office',
    testament: 'OT',
    alt_names: [],
    notes: 'Recognizable temple guild/service grouping (often descendants of Asaph, etc.).',
    example_refs: ['1 Chronicles 15', 'Ezra 2'],
  },
  {
    id: 'religious_office_nazirites',
    name: 'Nazirites',
    category: 'religious_office',
    testament: 'Both',
    alt_names: ['Nazarite (older spelling)'],
    notes: 'Vowed dedication group/category in Torah; echoed in NT contexts via vow language.',
    example_refs: ['Numbers 6', 'Acts 21'],
  },
  {
    id: 'ethnic_arabs',
    name: 'Arabs',
    category: 'ethnic_nation',
    testament: 'NT',
    alt_names: [],
    notes: 'Explicitly named in NT diaspora list.',
    example_refs: ['Acts 2'],
  },
  {
    id: 'clan_sabeans',
    name: 'Sabeans',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Sheba / people of Sheba (contextual)'],
    notes: 'Appears as a raiding people group (Job) and as a named people in prophetic texts.',
    example_refs: ['Job 1', 'Isaiah 45', 'Joel 3'],
  },
  {
    id: 'clan_dedanites',
    name: 'Dedanites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Dedan'],
    notes: 'Named people in genealogies and prophetic oracles.',
    example_refs: ['Genesis 10', 'Ezekiel 27'],
  },
  {
    id: 'clan_kedar',
    name: 'Kedarites (Kedar)',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Kedar'],
    notes: 'Desert people group named in prophetic/poetic texts.',
    example_refs: ['Isaiah 60', 'Psalm 120'],
  },
  {
    id: 'clan_hagrites',
    name: 'Hagrites (Hagarites)',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Hagarites'],
    notes: 'Named people group in Chronicles genealogical/war lists.',
    example_refs: ['1 Chronicles 5', 'Psalm 83'],
  },
  {
    id: 'clan_meunites',
    name: 'Meunites',
    category: 'ethnic_nation',
    testament: 'OT',
    alt_names: ['Mehunim (spelling variant in some contexts)'],
    notes: 'Named people group in OT narratives/lists.',
    example_refs: ['2 Chronicles 26', 'Ezra 2'],
  },
  {
    id: 'clan_shuhites',
    name: 'Shuhites',
    category: 'clan',
    testament: 'OT',
    alt_names: [],
    notes: 'Gentilic clan label (e.g., Bildad the Shuhite).',
    example_refs: ['Job 2'],
  },
  {
    id: 'clan_temanites',
    name: 'Temanites',
    category: 'clan',
    testament: 'OT',
    alt_names: [],
    notes: 'Gentilic clan label (e.g., Eliphaz the Temanite).',
    example_refs: ['Job 2', 'Obadiah 1'],
  },
  {
    id: 'clan_naamathites',
    name: 'Naamathites',
    category: 'clan',
    testament: 'OT',
    alt_names: [],
    notes: 'Gentilic clan label (e.g., Zophar the Naamathite).',
    example_refs: ['Job 2'],
  },
  {
    id: 'clan_buzites',
    name: 'Buzites',
    category: 'clan',
    testament: 'OT',
    alt_names: [],
    notes: 'Gentilic clan label (e.g., Elihu the Buzite).',
    example_refs: ['Job 32'],
  },
  {
    id: 'table_japheth_gomer',
    name: 'Gomer',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name functioning as a people-group label.',
    example_refs: ['Genesis 10', '1 Chronicles 1', 'Ezekiel 38'],
  },
  {
    id: 'table_japheth_ashkenaz',
    name: 'Ashkenaz',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name.',
    example_refs: ['Genesis 10', 'Jeremiah 51'],
  },
  {
    id: 'table_japheth_riphath',
    name: 'Riphath',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Diphath (1 Chr spelling variant)'],
    notes: 'Table of Nations people-name with spelling variation across parallel lists.',
    example_refs: ['Genesis 10', '1 Chronicles 1'],
  },
  {
    id: 'table_japheth_togarmah',
    name: 'Togarmah',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Beth-togarmah (place/people association)'],
    notes: 'Table of Nations people-name.',
    example_refs: ['Genesis 10', 'Ezekiel 27', 'Ezekiel 38'],
  },
  {
    id: 'table_japheth_magog',
    name: 'Magog',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name; used in later prophetic imagery.',
    example_refs: ['Genesis 10', 'Ezekiel 38'],
  },
  {
    id: 'table_japheth_madai',
    name: 'Madai',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Medes (later ethnic label)'],
    notes: 'Genealogical people-name connected with later Median identity in some readings.',
    example_refs: ['Genesis 10', 'Daniel 5'],
  },
  {
    id: 'table_japheth_javan',
    name: 'Javan',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Ionians / Greeks (often)'],
    notes: 'Genealogical people-name often associated with Greek-world identity in prophetic texts.',
    example_refs: ['Genesis 10', 'Isaiah 66', 'Ezekiel 27'],
  },
  {
    id: 'table_japheth_elishah',
    name: 'Elishah',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name.',
    example_refs: ['Genesis 10', 'Ezekiel 27'],
  },
  {
    id: 'table_japheth_tarshish',
    name: 'Tarshish',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Appears as place/people label in trade and voyage contexts.',
    example_refs: ['Genesis 10', 'Jonah 1', 'Ezekiel 27'],
  },
  {
    id: 'table_japheth_kittim',
    name: 'Kittim',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name; later used as a broad maritime/Greek-world label in some texts.',
    example_refs: ['Genesis 10', 'Numbers 24', 'Daniel 11'],
  },
  {
    id: 'table_japheth_dodanim',
    name: 'Dodanim',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Rodanim (spelling variant)'],
    notes: 'Table of Nations people-name with a common parallel-list spelling variant.',
    example_refs: ['Genesis 10', '1 Chronicles 1'],
  },
  {
    id: 'table_japheth_tubal',
    name: 'Tubal',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name; appears in prophetic trade/war lists.',
    example_refs: ['Genesis 10', 'Ezekiel 27', 'Ezekiel 38'],
  },
  {
    id: 'table_japheth_meshech',
    name: 'Meshech',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name; appears in prophetic lists.',
    example_refs: ['Genesis 10', 'Psalm 120', 'Ezekiel 38'],
  },
  {
    id: 'table_japheth_tiras',
    name: 'Tiras',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name.',
    example_refs: ['Genesis 10', '1 Chronicles 1'],
  },
  {
    id: 'table_ham_cush',
    name: 'Cush',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Genealogical people-name; related to Cushites as an ethnic label.',
    example_refs: ['Genesis 10', 'Isaiah 18'],
  },
  {
    id: 'table_ham_seba',
    name: 'Seba',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name.',
    example_refs: ['Genesis 10', 'Isaiah 43'],
  },
  {
    id: 'table_ham_havilah_hamline',
    name: 'Havilah (Ham-line)',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Appears in multiple genealogical contexts; this entry is the Ham-line Havilah in Genesis 10.',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_ham_sabtah',
    name: 'Sabtah',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name.',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_ham_raamah',
    name: 'Raamah',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name.',
    example_refs: ['Genesis 10', 'Ezekiel 27'],
  },
  {
    id: 'table_ham_sabteca',
    name: 'Sabteca',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name.',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_ham_sheba',
    name: 'Sheba',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Appears in genealogies and later narratives (e.g., Queen of Sheba; distinct from Sabeans as a people label in some contexts).',
    example_refs: ['Genesis 10', '1 Kings 10', 'Psalm 72'],
  },
  {
    id: 'table_ham_dedan',
    name: 'Dedan',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Appears in genealogies and later prophetic trade lists.',
    example_refs: ['Genesis 10', 'Ezekiel 27'],
  },
  {
    id: 'table_ham_mizraim',
    name: 'Mizraim',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Egypt (as a nation label)'],
    notes: 'Genealogical people-name corresponding to Egypt in many readings.',
    example_refs: ['Genesis 10', 'Psalm 105'],
  },
  {
    id: 'table_ham_ludim',
    name: 'Ludim',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name.',
    example_refs: ['Genesis 10', '1 Chronicles 1'],
  },
  {
    id: 'table_ham_anamim',
    name: 'Anamim',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name.',
    example_refs: ['Genesis 10', '1 Chronicles 1'],
  },
  {
    id: 'table_ham_lehabim',
    name: 'Lehabim',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name.',
    example_refs: ['Genesis 10', '1 Chronicles 1'],
  },
  {
    id: 'table_ham_naphtuhim',
    name: 'Naphtuhim',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name.',
    example_refs: ['Genesis 10', '1 Chronicles 1'],
  },
  {
    id: 'table_ham_pathrusim',
    name: 'Pathrusim',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name.',
    example_refs: ['Genesis 10', '1 Chronicles 1'],
  },
  {
    id: 'table_ham_casluhim',
    name: 'Casluhim',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name (noted near Philistine/Caphtor origins traditions in Genesis 10).',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_ham_caphtorim',
    name: 'Caphtorim',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Table of Nations people-name (see also Caphtorim as an ethnic label in later texts).',
    example_refs: ['Genesis 10', 'Deuteronomy 2'],
  },
  {
    id: 'table_ham_put',
    name: 'Put',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Putites (gentilic form, contextual)'],
    notes: 'Table of Nations people-name; appears in prophetic war lists.',
    example_refs: ['Genesis 10', 'Ezekiel 30', 'Nahum 3'],
  },
  {
    id: 'table_ham_canaan',
    name: 'Canaan (genealogical)',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Ancestor-name that also functions as a broad people-group label (Canaanites).',
    example_refs: ['Genesis 10', 'Genesis 12'],
  },
  {
    id: 'table_ham_sidon',
    name: 'Sidon (genealogical)',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: "Canaan's firstborn in Genesis 10; ties to Sidonians as a people label.",
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_ham_heth',
    name: 'Heth',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Hittites (linked in genealogical framing)'],
    notes: "Genealogical people-name behind 'sons of Heth\' phrasing.",
    example_refs: ['Genesis 10', 'Genesis 23'],
  },
  {
    id: 'table_ham_arkites',
    name: 'Arkites',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Genesis 10 Canaanite subgroup people-name.',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_ham_sinites',
    name: 'Sinites',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Genesis 10 Canaanite subgroup people-name.',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_ham_arvadites',
    name: 'Arvadites',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Arvad (island/city association)'],
    notes: 'Genesis 10 Canaanite subgroup people-name; appears in later trade lists.',
    example_refs: ['Genesis 10', 'Ezekiel 27'],
  },
  {
    id: 'table_ham_zemarites',
    name: 'Zemarites',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Genesis 10 Canaanite subgroup people-name.',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_ham_hamathites',
    name: 'Hamathites',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Hamath (city/people association)'],
    notes: 'Genesis 10 Canaanite subgroup people-name; Hamath also appears as a regional label later.',
    example_refs: ['Genesis 10', '2 Kings 14'],
  },
  {
    id: 'table_shem_elam',
    name: 'Elam',
    category: 'table_of_nations_people',
    testament: 'Both',
    alt_names: ['Elamites'],
    notes: 'Genealogical people-name; Elamites explicitly named in NT diaspora list.',
    example_refs: ['Genesis 10', 'Isaiah 11', 'Acts 2'],
  },
  {
    id: 'table_shem_asshur',
    name: 'Asshur',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Assyrians (linked)'],
    notes: 'Genealogical people-name tied to Assyrian identity in many readings.',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_shem_arphaxad',
    name: 'Arphaxad',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Genealogical people-name (often functions more as ancestry than later gentilic).',
    example_refs: ['Genesis 10', '1 Chronicles 1'],
  },
  {
    id: 'table_shem_lud',
    name: 'Lud',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Lydians (sometimes associated historically; Bible uses Lud/Ludim forms)'],
    notes: 'Genealogical people-name; do not confuse with Ludim (from Mizraim).',
    example_refs: ['Genesis 10', 'Ezekiel 27'],
  },
  {
    id: 'table_shem_aram',
    name: 'Aram',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Arameans (Syrians)'],
    notes: 'Genealogical people-name tied to Aramean identity.',
    example_refs: ['Genesis 10', 'Deuteronomy 26'],
  },
  {
    id: 'table_shem_uz',
    name: 'Uz',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Genealogical people-name; also associated with land of Uz in Job.',
    example_refs: ['Genesis 10', 'Job 1'],
  },
  {
    id: 'table_shem_hul',
    name: 'Hul',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Genealogical people-name.',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_shem_gether',
    name: 'Gether',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Genealogical people-name.',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_shem_mash',
    name: 'Mash',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Meshech (variant in some parallel lists)'],
    notes: 'Genealogical people-name with known parallel-list variation.',
    example_refs: ['Genesis 10', '1 Chronicles 1'],
  },
  {
    id: 'table_joktan_almodad',
    name: 'Almodad',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Joktan-line people-name (Genesis 10).',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_joktan_sheleph',
    name: 'Sheleph',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Joktan-line people-name (Genesis 10).',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_joktan_hazarmaveth',
    name: 'Hazarmaveth',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Joktan-line people-name (Genesis 10).',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_joktan_jerah',
    name: 'Jerah',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Joktan-line people-name (Genesis 10).',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_joktan_hadoram',
    name: 'Hadoram',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Joktan-line people-name (Genesis 10).',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_joktan_uzal',
    name: 'Uzal',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Joktan-line people-name (Genesis 10).',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_joktan_diklah',
    name: 'Diklah',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Joktan-line people-name (Genesis 10).',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_joktan_obal',
    name: 'Obal',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: ['Ebal (spelling variant in some lists)'],
    notes: 'Joktan-line people-name with possible parallel-list variation.',
    example_refs: ['Genesis 10', '1 Chronicles 1'],
  },
  {
    id: 'table_joktan_abimael',
    name: 'Abimael',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Joktan-line people-name (Genesis 10).',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_joktan_ophir',
    name: 'Ophir',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Joktan-line people-name; also appears as a trade/gold source in later narratives.',
    example_refs: ['Genesis 10', '1 Kings 9'],
  },
  {
    id: 'table_joktan_havilah_joktanline',
    name: 'Havilah (Joktan-line)',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Joktan-line Havilah (distinct genealogical placement from Ham-line Havilah).',
    example_refs: ['Genesis 10'],
  },
  {
    id: 'table_joktan_jobab',
    name: 'Jobab',
    category: 'table_of_nations_people',
    testament: 'OT',
    alt_names: [],
    notes: 'Joktan-line people-name (Genesis 10).',
    example_refs: ['Genesis 10'],
  },
];

const CATEGORY_LABELS = {
  covenant_identity: 'Covenant Identity',
  collective_label: 'Collective Label',
  tribe: 'Tribe',
  priestly_levitical: 'Priestly / Levitical',
  ethnic_nation: 'Ethnic Nation',
  empire_people: 'Empire People',
  regional_demonym: 'Regional Demonym',
  table_of_nations_people: 'Table of Nations People',
  clan: 'Clan',
  religious_sect: 'Religious Sect',
  political_party: 'Political Party',
  religious_office: 'Religious Office',
  civic_class: 'Civic Class',
  military_class: 'Military Class',
  movement: 'Movement',
};

function normalizeReference(ref) {
  return String(ref).replace(/[\u2013\u2014]/g, '-').replace(/\s+/g, ' ').trim();
}

function toTitleCase(text) {
  return String(text)
    .replace(/_/g, ' ')
    .replace(/\b\w/g, match => match.toUpperCase());
}

const groups = RAW_GROUPS.map(group => {
  const alt_names = Array.isArray(group.alt_names) ? group.alt_names : [];
  const example_refs = (group.example_refs || []).map(normalizeReference);
  const categoryLabel = CATEGORY_LABELS[group.category] || toTitleCase(group.category);

  return {
    ...group,
    alt_names,
    example_refs,
    categoryLabel,
    anchor: group.id,
  };
});

const categoryOrder = [];
const categoriesMap = {};

groups.forEach(group => {
  if (!categoriesMap[group.category]) {
    categoriesMap[group.category] = {
      id: group.category,
      label: group.categoryLabel,
      groups: [],
    };
    categoryOrder.push(group.category);
  }
  categoriesMap[group.category].groups.push(group);
});

const categories = categoryOrder.map(categoryId => {
  const category = categoriesMap[categoryId];
  category.groups.sort((a, b) => a.name.localeCompare(b.name));
  return category;
});

module.exports = {
  meta: META,
  groups,
  categories,
  categoryLabels: CATEGORY_LABELS,
};
